site_name: Griptape Docs
theme:
    name: material
    features:
        - content.code.copy
        - navigation.tabs
        - navigation.sections
        - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
- Home: "index.md"
- Getting Started: 
  - Documentation: "docs/index.md"
- Griptape: "index.md"
- Skatepark: "index.md"
- (old) Getting Started:
  - Overview: "getting_started/index.md"
  - Pipelines and Workflows: "getting_started/structures.md"
  - Memory: "getting_started/memory.md"
  - Tools: "getting_started/tools.md"
- (old) Tools:
  - Custom Tools: "tools/custom_tools.md"
  - Skatepark Tools:
      - AWS: "tools/skatepark_tools/aws.md"
      - Calculator: "tools/skatepark_tools/calculator.md"
      - DataScientist: "tools/skatepark_tools/data_scientist.md"
      - EmailSender: "tools/skatepark_tools/email_sender.md"
      - GoogleSearch: "tools/skatepark_tools/google_search.md"
      - GoogleSheets: "tools/skatepark_tools/google_sheets.md"
      - SqlClient: "tools/skatepark_tools/sql_client.md"
      - WebScraper: "tools/skatepark_tools/web_scraper.md"
      - Wiki: "tools/skatepark_tools/wiki.md"