site_name: Griptape Docs
extra:
  analytics:
    provider: google
    property: G-SYLLSDD3N1
theme:
    name: material
    features:
        - content.code.copy
        - navigation.tabs
        - navigation.sections
        - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
- griptape-flow:
  - Overview: "griptape_flow/index.md"
  - Quick Start: "griptape_flow/quick_start.md"
  - Pipelines: "griptape_flow/pipelines.md"
  - Workflows: "griptape_flow/workflows.md"
  - Serialization: "griptape_flow/serialization.md"
  - Memory: "griptape_flow/memory.md"
  - CoT and Tools: "griptape_flow/cot_and_tools.md"
- griptape-core:
  - Overview: "griptape_core/index.md"
  - Quick Start: "griptape_core/quick_start.md"
  - Custom Tools: "griptape_core/custom_tools.md"
- griptape-tools:
    - Overview: "griptape_tools/index.md"
    - AwsCli: "griptape_tools/official_tools/aws_cli.md"
    - Calculator: "griptape_tools/official_tools/calculator.md"
    - EmailClient: "griptape_tools/official_tools/email_client.md"
    - SqlClient: "griptape_tools/official_tools/sql_client.md"
    - WebScraper: "griptape_tools/official_tools/web_scraper.md"
    - WebSearch: "griptape_tools/official_tools/web_search.md"