site_name: Griptape Docs
plugins:
  - glightbox
extra:
  analytics:
    provider: google
    property: G-QM8EDPSCB6
theme:
    name: material
    logo: assets/griptape-logo.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - def_list
nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
    - FAQ: "faq.md"
- griptape-flow:
  - Overview: "griptape-flow/index.md"
  - Quick Start: "griptape-flow/quick-start.md"
  - Structures:
    - Pipelines: "griptape-flow/pipelines.md"
    - Workflows: "griptape-flow/workflows.md"
    - Serialization: "griptape-flow/serialization.md"
  - Prompt Drivers:
    - Overview: "griptape-flow/prompt-drivers/index.md"
    - OpenAI: "griptape-flow/prompt-drivers/openai.md"
    - Cohere: "griptape-flow/prompt-drivers/cohere.md"
    - Hugging Face Hub: "griptape-flow/prompt-drivers/hugging-face-hub.md"
    - Hugging Face Pipeline: "griptape-flow/prompt-drivers/hugging-face-pipeline.md"
  - Memory: "griptape-flow/memory.md"
  - CoT and Tools: "griptape-flow/cot-and-tools.md"
- griptape-core:
  - Overview: "griptape-core/index.md"
  - Quick Start: "griptape-core/quick-start.md"
  - Custom Tools: "griptape-core/custom-tools.md"
- griptape-tools:
    - Overview: "griptape-tools/overview.md"
    - AwsCli: "griptape-tools/official-tools/aws-cli.md"
    - Calculator: "griptape-tools/official-tools/calculator.md"
    - EmailClient: "griptape-tools/official-tools/email-client.md"
    - SqlClient: "griptape-tools/official-tools/sql-client.md"
    - WebScraper: "griptape-tools/official-tools/web-scraper.md"
    - WebSearch: "griptape-tools/official-tools/web-search.md"