site_name: Griptape Docs
theme:
    name: material
    features:
        - content.code.copy
        - navigation.tabs
        - navigation.sections
        - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
- Griptape:
  - Overview: "griptape/index.md"
  - Quick Start: "griptape/quick_start.md"
  - Custom Tools: "griptape/tools/custom_tools.md"
  - Official Tools:
      - AwsCli: "griptape/tools/official_tools/aws_cli.md"
      - Calculator: "griptape/tools/official_tools/calculator.md"
      - EmailClient: "griptape/tools/official_tools/email_client.md"
      - SqlClient: "griptape/tools/official_tools/sql_client.md"
      - WebScraper: "griptape/tools/official_tools/web_scraper.md"
      - WebSearch: "griptape/tools/official_tools/web_search.md"
- Skatepark:
  - Overview: "skatepark/index.md"
  - Quick Start: "skatepark/quick_start.md"
  - Pipelines and Workflows: "skatepark/structures.md"
  - Memory: "skatepark/memory.md"
  - Tools: "skatepark/tools.md"